CREATE TABLE process_route_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    route_code VARCHAR(64) NOT NULL,
    route_name VARCHAR(128) NOT NULL,
    product_type VARCHAR(64) NULL,
    description VARCHAR(500) NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_route_template_code (tenant_id, route_code, delete_marker),
    KEY idx_route_template_product (tenant_id, product_type, enabled, deleted)
);

CREATE TABLE process_step_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    route_template_id BIGINT NOT NULL,
    step_code VARCHAR(64) NOT NULL,
    step_name VARCHAR(128) NOT NULL,
    step_order INT NOT NULL,
    assigned_role VARCHAR(64) NOT NULL,
    photo_required TINYINT NOT NULL DEFAULT 0,
    remark_required TINYINT NOT NULL DEFAULT 0,
    mobile_enabled TINYINT NOT NULL DEFAULT 1,
    estimated_hours DECIMAL(10, 2) NULL,
    operation_instruction VARCHAR(1000) NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_step_template_active_order (tenant_id, route_template_id, step_order, delete_marker),
    UNIQUE KEY uk_step_template_code (tenant_id, route_template_id, step_code, delete_marker),
    KEY idx_step_template_route (tenant_id, route_template_id, enabled, deleted)
);
