CREATE TABLE production_route_instance (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    source_route_template_id BIGINT NOT NULL,
    source_route_template_version INT NULL,
    route_code_snapshot VARCHAR(64) NOT NULL,
    route_name_snapshot VARCHAR(128) NOT NULL,
    product_type_snapshot VARCHAR(64) NULL,
    route_description_snapshot VARCHAR(500) NULL,
    status VARCHAR(32) NOT NULL,
    production_progress DECIMAL(5, 2) NOT NULL DEFAULT 0,
    frozen TINYINT NOT NULL DEFAULT 1,
    dispatched_by BIGINT NULL,
    dispatched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idempotency_key VARCHAR(128) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_production_route_order_item (tenant_id, order_item_id, delete_marker),
    KEY idx_production_route_order (tenant_id, order_id, order_item_id, deleted),
    KEY idx_production_route_status (tenant_id, status, deleted)
);

CREATE TABLE production_step_instance (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    route_instance_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    source_step_template_id BIGINT NULL,
    step_code_snapshot VARCHAR(64) NULL,
    step_name VARCHAR(128) NOT NULL,
    step_order INT NOT NULL,
    assigned_role VARCHAR(64) NOT NULL,
    assigned_user_id BIGINT NULL,
    photo_required TINYINT NOT NULL DEFAULT 0,
    remark_required TINYINT NOT NULL DEFAULT 0,
    mobile_enabled TINYINT NOT NULL DEFAULT 1,
    estimated_hours DECIMAL(10, 2) NULL,
    operation_instruction VARCHAR(1000) NULL,
    status VARCHAR(32) NOT NULL,
    frozen TINYINT NOT NULL DEFAULT 1,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_production_step_order (tenant_id, route_instance_id, step_order, delete_marker),
    KEY idx_production_step_route (tenant_id, route_instance_id, status, deleted),
    KEY idx_production_step_order_item (tenant_id, order_item_id, status, deleted)
);
