CREATE TABLE production_work_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    work_order_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    production_route_instance_id BIGINT NULL,
    order_item_name_snapshot VARCHAR(128) NOT NULL,
    product_type_snapshot VARCHAR(64) NULL,
    quantity_snapshot DECIMAL(18, 2) NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NULL,
    instruction_title VARCHAR(128) NULL,
    instruction_remark VARCHAR(1000) NULL,
    production_requirement VARCHAR(1000) NULL,
    quality_requirement VARCHAR(1000) NULL,
    packaging_requirement VARCHAR(1000) NULL,
    shipping_requirement VARCHAR(1000) NULL,
    delivery_requirement VARCHAR(1000) NULL,
    planned_start_date DATE NULL,
    planned_finish_date DATE NULL,
    required_delivery_date DATE NULL,
    deadline_remark VARCHAR(500) NULL,
    equipment_model VARCHAR(128) NULL,
    technical_config_summary VARCHAR(500) NULL,
    technical_config_remark VARCHAR(1000) NULL,
    technical_config_json TEXT NULL,
    responsible_user_id BIGINT NULL,
    handler_user_id BIGINT NULL,
    production_manager_id BIGINT NULL,
    primary_worker_id BIGINT NULL,
    released_by BIGINT NULL,
    released_at DATETIME NULL,
    confirmed_by BIGINT NULL,
    confirmed_at DATETIME NULL,
    production_signed_by BIGINT NULL,
    production_signed_at DATETIME NULL,
    warehouse_confirmed_by BIGINT NULL,
    warehouse_confirmed_at DATETIME NULL,
    quality_confirmed_by BIGINT NULL,
    quality_confirmed_at DATETIME NULL,
    customer_acceptance_required TINYINT NOT NULL DEFAULT 0,
    acceptance_remark VARCHAR(1000) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_production_work_order_no (tenant_id, work_order_no),
    KEY idx_production_work_order_item (tenant_id, order_item_id, deleted),
    KEY idx_production_work_order_status (tenant_id, status, deleted),
    KEY idx_production_work_order_route (tenant_id, production_route_instance_id)
);

CREATE TABLE production_work_order_material (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    work_order_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    material_id BIGINT NULL,
    material_code VARCHAR(64) NULL,
    material_name VARCHAR(128) NOT NULL,
    spec VARCHAR(255) NULL,
    unit VARCHAR(32) NULL,
    required_qty DECIMAL(18, 4) NOT NULL,
    usage_stage VARCHAR(128) NULL,
    related_step_template_id BIGINT NULL,
    related_step_instance_id BIGINT NULL,
    requirement_status VARCHAR(32) NOT NULL,
    remark VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_production_work_order_material_work_order (tenant_id, work_order_id, deleted),
    KEY idx_production_work_order_material_material (tenant_id, material_id, deleted),
    KEY idx_production_work_order_material_order_item (tenant_id, order_item_id, deleted),
    KEY idx_production_work_order_material_step_instance (tenant_id, related_step_instance_id, deleted)
);
