CREATE TABLE process_step_material_requirement_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL DEFAULT 1,
    route_template_id BIGINT NOT NULL,
    step_template_id BIGINT NOT NULL,
    material_id BIGINT NULL,
    material_code VARCHAR(64) NULL,
    material_name VARCHAR(128) NOT NULL,
    spec VARCHAR(255) NULL,
    unit VARCHAR(32) NOT NULL,
    base_qty_per_unit DECIMAL(18, 4) NULL,
    fixed_qty DECIMAL(18, 4) NULL,
    loss_rate DECIMAL(10, 4) NULL,
    required_qty_expression VARCHAR(500) NULL,
    usage_stage VARCHAR(128) NULL,
    remark VARCHAR(500) NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    delete_marker BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_step_material_route (tenant_id, route_template_id, deleted),
    KEY idx_step_material_step (tenant_id, step_template_id, enabled, deleted),
    KEY idx_step_material_material (tenant_id, material_id, deleted)
);
